// <auto-generated />
using System;
using HookFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HookFlow.Infrastructure.Migrations
{
    [DbContext(typeof(HookFlowDbContext))]
    [Migration("20260525063044_AddMaxRetryAttemptsToEvent")]
    partial class AddMaxRetryAttemptsToEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HookFlow.Domain.Entities.ProcessingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("WebhookEventId")
                        .HasDatabaseName("idx_attempts_event_id");

                    b.HasIndex("WebhookEventId", "AttemptNumber")
                        .HasDatabaseName("idx_attempts_event_number");

                    b.ToTable("ProcessingAttempts");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_projects_created_at");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_projects_owner_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_projects_status");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_users_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AllowedEventTypes")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RejectInvalidSignature")
                        .HasColumnType("boolean");

                    b.Property<string>("RetryStrategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SignatureHeaderName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("X-Webhook-Signature");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VerifySignature")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_endpoints_is_active");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_endpoints_project_id");

                    b.HasIndex("Provider")
                        .HasDatabaseName("idx_endpoints_provider");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_endpoints_slug");

                    b.ToTable("WebhookEndpoints");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<bool?>("SignatureValid")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId")
                        .HasDatabaseName("idx_events_endpoint_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("idx_events_event_type");

                    b.HasIndex("ExternalEventId")
                        .HasDatabaseName("idx_events_external_event_id")
                        .HasFilter("\"ExternalEventId\" IS NOT NULL");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("idx_events_next_retry_at")
                        .HasFilter("\"Status\" = 'Retrying'");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("idx_events_received_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_events_status");

                    b.HasIndex("EndpointId", "Status")
                        .HasDatabaseName("idx_events_endpoint_status");

                    b.HasIndex("Status", "ReceivedAt")
                        .HasDatabaseName("idx_events_status_received");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.ProcessingAttempt", b =>
                {
                    b.HasOne("HookFlow.Domain.Entities.WebhookEvent", "WebhookEvent")
                        .WithMany("ProcessingAttempts")
                        .HasForeignKey("WebhookEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebhookEvent");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.Project", b =>
                {
                    b.HasOne("HookFlow.Domain.Entities.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.HasOne("HookFlow.Domain.Entities.Project", "Project")
                        .WithMany("Endpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.WebhookEvent", b =>
                {
                    b.HasOne("HookFlow.Domain.Entities.WebhookEndpoint", "Endpoint")
                        .WithMany("Events")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.Project", b =>
                {
                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.WebhookEndpoint", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("HookFlow.Domain.Entities.WebhookEvent", b =>
                {
                    b.Navigation("ProcessingAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
