# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore HookFlow.slnx
RUN dotnet publish HookFlow.Api/HookFlow.Api.csproj -c Release -o /app/publish

# Stage 2: Runtime  
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5000
ENTRYPOINT ["dotnet", "HookFlow.Api.dll"]
