import type { WebhookEvent, WebhookEndpoint, Project, DashboardSummary, ProcessingAttempt } from '@/types/event.types'

// ─── Mock Projects ────────────────────────────────────────────────
export const mockProjects: Project[] = [
  {
    id: 'proj_001',
    name: 'Alpha E-commerce',
    description: 'Payment and order lifecycle webhooks',
    status: 'Active',
    endpointCount: 4,
    eventCount: 1284,
    failureRate: 0.031,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-23T08:00:00Z',
  },
  {
    id: 'proj_002',
    name: 'GitHub Monitor',
    description: 'Track push events, PRs and deployments',
    status: 'Active',
    endpointCount: 2,
    eventCount: 456,
    failureRate: 0.004,
    createdAt: '2026-05-05T09:00:00Z',
    updatedAt: '2026-05-22T14:00:00Z',
  },
  {
    id: 'proj_003',
    name: 'CI/CD Pipeline',
    description: 'Deployment status and build notifications',
    status: 'Active',
    endpointCount: 3,
    eventCount: 312,
    failureRate: 0.012,
    createdAt: '2026-05-08T11:00:00Z',
    updatedAt: '2026-05-21T16:00:00Z',
  },
  {
    id: 'proj_004',
    name: 'Payment Demo',
    description: 'Demo integration for payment gateway testing',
    status: 'Inactive',
    endpointCount: 1,
    eventCount: 88,
    failureRate: 0.182,
    createdAt: '2026-05-10T13:00:00Z',
    updatedAt: '2026-05-15T10:00:00Z',
  },
]

// ─── Mock Endpoints ───────────────────────────────────────────────
export const mockEndpoints: WebhookEndpoint[] = [
  {
    id: 'ep_001',
    projectId: 'proj_001',
    projectName: 'Alpha E-commerce',
    name: 'Payment Success',
    slug: 'payment-success',
    webhookUrl: 'http://localhost:5000/api/incoming-webhooks/payment-success',
    provider: 'GenericHmac',
    isActive: true,
    allowedEventTypes: ['payment.success', 'payment.failed'],
    maxRetryAttempts: 5,
    signatureHeaderName: 'X-Webhook-Signature',
    rejectInvalidSignature: true,
    eventsToday: 28,
    failureRate: 0.035,
    lastReceivedAt: '2026-05-24T08:15:00Z',
    createdAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'ep_002',
    projectId: 'proj_001',
    projectName: 'Alpha E-commerce',
    name: 'Order Created',
    slug: 'order-created',
    webhookUrl: 'http://localhost:5000/api/incoming-webhooks/order-created',
    provider: 'GenericHmac',
    isActive: true,
    allowedEventTypes: ['order.created', 'order.updated'],
    maxRetryAttempts: 3,
    signatureHeaderName: 'X-Webhook-Signature',
    rejectInvalidSignature: false,
    eventsToday: 12,
    failureRate: 0.008,
    lastReceivedAt: '2026-05-24T07:45:00Z',
    createdAt: '2026-05-01T10:05:00Z',
  },
  {
    id: 'ep_003',
    projectId: 'proj_002',
    projectName: 'GitHub Monitor',
    name: 'Push Events',
    slug: 'github-push',
    webhookUrl: 'http://localhost:5000/api/incoming-webhooks/github-push',
    provider: 'GitHub',
    isActive: true,
    allowedEventTypes: ['push', 'pull_request'],
    maxRetryAttempts: 3,
    signatureHeaderName: 'X-Hub-Signature-256',
    rejectInvalidSignature: true,
    eventsToday: 5,
    failureRate: 0.0,
    lastReceivedAt: '2026-05-24T06:30:00Z',
    createdAt: '2026-05-05T09:00:00Z',
  },
]

// ─── Mock Processing Attempts ────────────────────────────────────
const mockAttempts: ProcessingAttempt[] = [
  {
    id: 'att_001',
    attemptNumber: 1,
    status: 'Failed',
    startedAt: '2026-05-24T08:00:10Z',
    finishedAt: '2026-05-24T08:00:13Z',
    durationMs: 3001,
    errorMessage: 'Database connection timeout: exceeded 3s limit',
    workerName: 'worker-1',
  },
  {
    id: 'att_002',
    attemptNumber: 2,
    status: 'Failed',
    startedAt: '2026-05-24T08:01:10Z',
    finishedAt: '2026-05-24T08:01:12Z',
    durationMs: 2500,
    errorMessage: 'Email service unavailable: SMTP connection refused',
    workerName: 'worker-1',
  },
  {
    id: 'att_003',
    attemptNumber: 3,
    status: 'Success',
    startedAt: '2026-05-24T08:06:10Z',
    finishedAt: '2026-05-24T08:06:10Z',
    durationMs: 145,
    errorMessage: null,
    workerName: 'worker-2',
  },
]

// ─── Mock Events ──────────────────────────────────────────────────
export const mockEvents: WebhookEvent[] = [
  {
    id: 'evt_001',
    externalEventId: null,
    eventType: 'payment.success',
    endpointId: 'ep_001',
    endpointName: 'Payment Success',
    endpointSlug: 'payment-success',
    projectId: 'proj_001',
    projectName: 'Alpha E-commerce',
    provider: 'GenericHmac',
    status: 'Processed',
    signatureValid: true,
    retryCount: 2,
    nextRetryAt: null,
    errorMessage: null,
    sourceIp: '192.168.1.100',
    payloadJson: {
      event: 'payment.success',
      orderId: 'ORD-2026-001',
      amount: 350000,
      currency: 'VND',
      transactionId: 'TXN-88421',
      customer: { name: 'Nguyen Van A', email: 'nguyenvana@example.com' },
      metadata: { source: 'web', gateway: 'vnpay' },
    },
    headersJson: {
      'content-type': 'application/json',
      'x-webhook-event': 'payment.success',
      'x-webhook-signature': 'sha256=abc123def456abc123def456',
      'user-agent': 'PaymentProvider/1.0',
      'x-request-id': 'req_88421',
    },
    receivedAt: '2026-05-24T08:06:00Z',
    processedAt: '2026-05-24T08:06:10Z',
    durationMs: 145,
    processingAttempts: mockAttempts,
  },
  {
    id: 'evt_002',
    externalEventId: null,
    eventType: 'github.push',
    endpointId: 'ep_003',
    endpointName: 'Push Events',
    endpointSlug: 'github-push',
    projectId: 'proj_002',
    projectName: 'GitHub Monitor',
    provider: 'GitHub',
    status: 'Processed',
    signatureValid: true,
    retryCount: 0,
    nextRetryAt: null,
    errorMessage: null,
    sourceIp: '140.82.112.25',
    payloadJson: {
      ref: 'refs/heads/main',
      repository: { name: 'hookflow', full_name: 'phanhoaian1203/hookflow' },
      pusher: { name: 'phanhoaian1203', email: 'dev@example.com' },
      commits: [
        { id: 'abc123', message: 'feat(frontend): add landing page', author: { name: 'Phan Hoa Ian' } },
      ],
    },
    headersJson: {
      'content-type': 'application/json',
      'x-github-event': 'push',
      'x-hub-signature-256': 'sha256=xyz789',
      'user-agent': 'GitHub-Hookshot/abc123',
    },
    receivedAt: '2026-05-24T07:45:00Z',
    processedAt: '2026-05-24T07:45:02Z',
    durationMs: 88,
    processingAttempts: [mockAttempts[2]],
  },
  {
    id: 'evt_003',
    externalEventId: null,
    eventType: 'order.created',
    endpointId: 'ep_002',
    endpointName: 'Order Created',
    endpointSlug: 'order-created',
    projectId: 'proj_001',
    projectName: 'Alpha E-commerce',
    provider: 'GenericHmac',
    status: 'Retrying',
    signatureValid: true,
    retryCount: 2,
    nextRetryAt: '2026-05-24T09:00:00Z',
    errorMessage: 'Failed to update inventory: service timeout',
    sourceIp: '10.0.0.55',
    payloadJson: {
      event: 'order.created',
      orderId: 'ORD-2026-002',
      items: [{ sku: 'SKU-001', qty: 2, price: 150000 }],
      total: 300000,
    },
    headersJson: { 'content-type': 'application/json', 'x-webhook-event': 'order.created' },
    receivedAt: '2026-05-24T07:30:00Z',
    processedAt: null,
    durationMs: null,
    processingAttempts: [mockAttempts[0], mockAttempts[1]],
  },
  {
    id: 'evt_004',
    externalEventId: null,
    eventType: 'payment.failed',
    endpointId: 'ep_001',
    endpointName: 'Payment Success',
    endpointSlug: 'payment-success',
    projectId: 'proj_001',
    projectName: 'Alpha E-commerce',
    provider: 'GenericHmac',
    status: 'Dead',
    signatureValid: true,
    retryCount: 5,
    nextRetryAt: null,
    errorMessage: 'Max retry attempts (5) exceeded. Last error: Database unavailable',
    sourceIp: '192.168.1.100',
    payloadJson: { event: 'payment.failed', orderId: 'ORD-2026-003', reason: 'insufficient_funds' },
    headersJson: { 'content-type': 'application/json', 'x-webhook-event': 'payment.failed' },
    receivedAt: '2026-05-24T06:00:00Z',
    processedAt: null,
    durationMs: null,
    processingAttempts: [],
  },
  {
    id: 'evt_005',
    externalEventId: null,
    eventType: 'deployment.finished',
    endpointId: 'ep_003',
    endpointName: 'Push Events',
    endpointSlug: 'github-push',
    projectId: 'proj_003',
    projectName: 'CI/CD Pipeline',
    provider: 'CiCd',
    status: 'InvalidSignature',
    signatureValid: false,
    retryCount: 0,
    nextRetryAt: null,
    errorMessage: 'HMAC signature mismatch — request rejected',
    sourceIp: '20.80.10.5',
    payloadJson: { event: 'deployment.finished', service: 'backend-api', version: 'v1.2.3', status: 'success' },
    headersJson: { 'content-type': 'application/json', 'x-webhook-signature': 'sha256=invalid_sig' },
    receivedAt: '2026-05-24T05:30:00Z',
    processedAt: null,
    durationMs: null,
  },
  {
    id: 'evt_006',
    externalEventId: null,
    eventType: 'payment.success',
    endpointId: 'ep_001',
    endpointName: 'Payment Success',
    endpointSlug: 'payment-success',
    projectId: 'proj_001',
    projectName: 'Alpha E-commerce',
    provider: 'GenericHmac',
    status: 'Pending',
    signatureValid: true,
    retryCount: 0,
    nextRetryAt: null,
    errorMessage: null,
    sourceIp: '192.168.1.100',
    payloadJson: { event: 'payment.success', orderId: 'ORD-2026-004', amount: 750000 },
    headersJson: { 'content-type': 'application/json' },
    receivedAt: '2026-05-24T08:20:00Z',
    processedAt: null,
    durationMs: null,
  },
]

// ─── Mock Dashboard Summary ───────────────────────────────────────
export const mockDashboardSummary: DashboardSummary = {
  totalEvents: 1284,
  processedEvents: 1198,
  failedEvents: 48,
  retryingEvents: 23,
  deadEvents: 12,
  pendingEvents: 3,
  failureRate: 0.037,
  avgProcessingTimeMs: 234,
  eventsToday: 87,
}
